### ISSUE TITLE
origin/release README.md

### ISSUE THREAD

**Issue by jwu910** [jwu910/photo-booth-automation#15]
https://github.com/jwu910/photo-booth-automation/blob/release/README.md

File contains unresolved merge conflicts.

**Comment by rainrivas** [comment]
@jwu910 I got this, easy breezy

**Comment by jwu910** [comment]
Hahah I was gonna ask if we needed to branch to fix becuase i pushed it to release

**Comment by rainrivas** [comment]
@jwu910 yeah I branched to fix. If you don't want the merge commit you can merge it in a FF style (rebase-merge) or squash it into 1 commit (merge commits would show 2 commits. The 1 change and the 'merge-commit')
